import Head from "next/head";
import { useRouter } from "next/router";
import { Button, Image } from "ui";
import { withLayout } from "../components/Layout";
import styles from "../styles/Home.module.css";

function Home() {
  const router = useRouter();
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Image
          src="/landing_img.png"
          width={360}
          preview={true}
          rel="Login image"
        />
        <br />
        <h2>Schedule & Manage Pickups</h2>
        <span>
          Schedule one-time pickups or create a Recurring schedule. Add cleaning
          notes. Change Delivery locations and payment methods Or even
          reschedule with one tap
        </span>
        <br />
        <br />
        <Button
          type="ghost"
          className={styles.ghost_btn}
          size="large"
          block
          onClick={() => router.push("/signup?stage=1")}
        >
          Log in Via SMS
        </Button>
        <br />
        <Button type="ghost" className={styles.normal_btn} size="large" block>
          Log in Via Email
        </Button>
      </main>
    </div>
  );
}

export default withLayout(Home);
