import Head from "next/head";
import Link from "next/link";
import { useRouter } from "next/router";
import { Button, Input } from "ui";
import { withLayout } from "../components/Layout";
import styles from "../styles/Home.module.css";

function Home() {
  const router = useRouter();
  const {
    query: { stage },
  } = router;
  return (
    <div className={styles.container}>
      <Head>
        <title>Schedule your next chore on us</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>{stage == "1" && <Stage1Signup />}</main>
    </div>
  );
}

const Stage1Signup = () => (
  <>
    <h2>Get Started</h2>
    <span>Enter your details to get started</span>
    <br />
    <Input
      className={styles.textfield_rounded}
      size="large"
      type="text"
      placeholder="Phone number"
    />
    <br />
    <Input
      className={styles.textfield_rounded}
      size="large"
      type="password"
      placeholder="Password"
    />
    <br />
    <br />
    <Button className={styles.normal_btn} size="large" block>
      Get Started
    </Button>
    <br />
    <span>
      Don’t have an account?{" "}
      <Link href="/signup_2" passHref>
        <a>Sign Up</a>
      </Link>
    </span>
  </>
);

const Stage2Signup = () => (
  <>
    <h2>Tell us more about you</h2>
    <span>
      There are 892 people in your area using our app. Join them today
    </span>
    <br />
    <Input
      className={styles.textfield_rounded}
      size="large"
      type="text"
      placeholder="Phone number"
    />
    <br />
    <Input
      className={styles.textfield_rounded}
      size="large"
      type="password"
      placeholder="Password"
    />
    <br />
    <Button className={styles.normal_btn} size="large" block>
      Get Started
    </Button>
    <br />
    <span>
      Don’t have an account?{" "}
      <Link href="/" passHref>
        <a>Log In</a>
      </Link>
    </span>
  </>
);

export default withLayout(Home);
